layout_spectrum: 0.3530466
typography_spectrum: 0.8228811
color:
  saturation: 0.8064516
  brandStrength: 0.9555789
  lightness: 0.374552
  rhythmicContrast: 0.853925
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Jones-warren
